# Project Information
site_name: b1b1's share
site_description: Kernel, Blockchain, CTF Crypto&PWN
site_author: b1b1
site_url: https://beafb1b1.github.io/

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true

# Repository
repo_name: 'beafb1b1/beafb1b1.github.io'
repo_url: 'https://github.com/beafb1b1/beafb1b1.github.io/'
edit_uri: 'blob/dev/docs/'

# Copyright
copyright: 'Copyright &copy; b1b1@r3kapig'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - home: index.md
    - linux kernel:
        - linux内核基础: kernel/linux_kernel_base.md
        - CISCN2017 babydriver(UAF): kernel/ciscn_2017_babydriver_UAF.md
        - QWB2018 core(ROP): kernel/qwb_2018_core_ROP.md
        - CISCN2017 babydriver(ROP): kernel/ciscn_2017_babydriver_ROP_bypass_smep.md
        - QWB2018 core(ret2usr): kernel/qwb_2018_core_ret2usr.md
        - 0CTF2018 babykernel(DF): kernel/0ctf2018_babykernel_double_fetch.md
        - STARCTF2019 hackme(ARW): kernel/starctf2019_hackeme_arw.md
        - RW BPF(Integer Overflow): kernel/BPF_IntOF.md
    - blockchain:
        - 资料收集: blockchain/collision.md
        - RWCTF2019 bank: blockchain/realworldctf_2019_bank.md
        - N1CTF2019 h4ck Smart Contract: blockchain/n1ctf_2019_smartcontract.md
        - HCTF2018 ez2win: blockchain/hctf_2018_ez2win.md
        - BCTF2018 Fake3d&EOSGAME: blockchain/bctf2018_fake3d_eosgame.md
        - CISCN 2019 Daysbank: blockchain/ciscn2019_daysbank.md
        - QWB 2019 babybank&babybet: blockchain/qwb2019_babybank_babybet.md
        - ByteCTF 2019 bet&hf: blockchain/byte2019_bet_hf.md
        - 数字经济 2019 jojo: blockchain/szjj_2019_jojo.md
    - backup:
        - RWCTF2018 station-escape: backup/realworldctf_2018_stationescape.md
        - gitpage采坑: backup/gitpage_fuck.md