# Project Information
site_name: b1b1's share
site_description: Kernel, Blockchain, CTF Crypto&PWN
site_author: b1b1
site_url: https://beafb1b1.github.io/
theme:
  name: 'material'

# Repository
repo_name: 'beafb1b1/share'
repo_url: 'https://github.com/beafb1b1/share/'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2019- 2020 b1b1@r3kapig'

nav:
    - home: index.md
    - kernel:
        - linux内核基础: kernel/linux_kernel_base.md
    - blockchain:
        - RWCTF2019 bank: blockchain/realworldctf_2019_bank.md
    - vmescape:
        - RWCTF2018 station-escape: vmescape/realworldctf_2018_stationescape.md